# permissions for end users to view blackboxmodules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: blackbox-module-operator
    app.kubernetes.io/managed-by: kustomize
  name: blackboxmodule-viewer-role
rules:
- apiGroups:
  - module.monitoring.ruup.amadeus.net
  resources:
  - blackboxmodules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - module.monitoring.ruup.amadeus.net
  resources:
  - blackboxmodules/status
  verbs:
  - get
