---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - module.monitoring.ruup.amadeus.net
  resources:
  - blackboxmodules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - module.monitoring.ruup.amadeus.net
  resources:
  - blackboxmodules/finalizers
  verbs:
  - update
- apiGroups:
  - module.monitoring.ruup.amadeus.net
  resources:
  - blackboxmodules/status
  verbs:
  - get
  - patch
  - update
